"""Monero address encoding, and the shared 2-of-2 spend key a GRC<->XMR swap locks to.

Role: submodule (it holds two decisions -- is this address well formed and on the
      expected network, and what is the shared key for these two shares -- and
      both are pure functions of their arguments)
Reads: nothing. No socket, no file, no environment, no clock, no wallet RPC.
Writes: nothing
Can move funds: no directly, and this is the field that needs the longest answer.
      Nothing here signs, broadcasts, or opens a wallet. It is nonetheless the
      most fund-critical file in the Monero work, because `shared_address` decides
      WHERE the XMR in a swap is locked. A defect there does not produce an error;
      it produces a valid Monero address whose spend key nobody holds, and the
      coins are gone with no transaction to point at. That is the failure mode
      docs/dleq_cross_curve_design.md section 7.4 names as the reason a broken
      cross-curve swap is worse than a custodial one: "the symptom arrives after
      the money moved, and on first sight it reads as a stuck swap."
Mainnet-safe: yes to run -- it cannot reach a network. `decode_address` will tell
      you an address is MAINNET, in capitals, and no function here defaults to
      mainnet: `network` is a required argument everywhere it matters.
Live-safe: yes.

WHY THIS EXISTS RATHER THAN CALLING THE WALLET

`chains/monero.py` already asks monero-wallet-rpc for address work --
`create_address`, `validate_address`, `get_address` -- and that is the right place
for every ordinary address. This file is for the one address the wallet CANNOT
build.

An atomic GRC<->XMR swap locks the Monero to a key that is the SUM of two shares,
one per party, so that neither side alone can spend it and either side can once it
learns the other's share. No wallet holds both halves, which is the entire point,
so no wallet can be asked for the address. It has to be constructed from two
public keys client-side, by both parties independently, and they have to agree
byte for byte or the swap is locked to two different places.

That makes agreement, not correctness-in-isolation, the property that matters, and
it is why every constant below is derived or measured rather than recalled.

WHAT IS VERIFIED HERE, AND WHAT IS NOT (rule 17)

VERIFIED, against a real stagenet address generated by a real Monero wallet
(the one in docs/monero_stagenet_funding.md), on 2026-09-27:

    95 characters -> 9 base58 blocks (eight of 11 chars, one of 7) -> 69 bytes
    network byte      24            stagenet primary
    spend pubkey      22089d0c...   canonical, on-curve, torsion-free
    view  pubkey      81bf455a...   canonical, on-curve, torsion-free
    checksum on wire  ecd59b10
    Keccak-256(body)[:4] recomputed ecd59b10   -- MATCH

That single check exercises the base58 block decoder, the block-size table, the
body layout and the Keccak-256 checksum together, against bytes this session did
not produce. It is the strongest offline evidence available for this file, and it
is why the stagenet address is embedded in the test rather than a synthetic one.

ALL NINE NETWORK BYTES ARE NOW READ OUT OF MONERO'S SOURCE rather than recalled --
cryptonote_config.h lines 227-229, 270-272 and 285-287 on release-v0.18, fetched
2026-09-27 -- and every one matched what this table already said. Two of the nine
additionally have a real wallet-generated address behind them. The two grades are
kept as separate fields (`from_source`, `from_address`) rather than one `verified`
boolean, because reading a constant out of a header and decoding a real address are
different evidence and "I have a reason to believe it" must not be written in the
same voice as "I checked it". A test asserts the split.

REGTEST USES THE MAINNET PREFIXES: `case FAKECHAIN: return mainnet;`
(cryptonote_config.h:361). That is why a regtest wallet's address decodes here as
mainnet/primary, and it is why monero_shared_key_verify.py must build its shared
address with mainnet prefixes when the daemon reports fakechain.

THE SHARED-ADDRESS ARITHMETIC IS CONFIRMED AGAINST MONERO'S OWN WALLET, 2026-09-27.

This is the cross-check that was missing and it turned out to be free. `monero-wallet-rpc`'s
`generate_from_keys` takes an address, a spend key and a view key and returns the
address IT derives. Run on the operator's host against a regtest chain
(monero_shared_key_verify.py --run), with four freshly sampled shares:

    public spend key (sum)  2168ee3cb850808bf2bb431eab05e76f24e4ebac1851c566b92c33aa397f4895
    public view  key (sum)  436874fa37511b9f66a9beebac062fb7be798bb579bc4a0dceab2b1dd2f63260

    this repo computed  42tYMtaj4PRQQg1UPd3xr2KbEkqgwCjNcJBYcL112kDVRy3PHYgWvi6TfPbkmpAs3UXjYkNcEXwRb3JwzQXKuzXbBsPCKbZ
    the wallet derived  42tYMtaj4PRQQg1UPd3xr2KbEkqgwCjNcJBYcL112kDVRy3PHYgWvi6TfPbkmpAs3UXjYkNcEXwRb3JwzQXKuzXbBsPCKbZ
    IDENTICAL, and the wallet reported "Wallet has been generated successfully."

So `shared_public_key()`, `shared_private_spend_key()` and `encode_address()` agree
with Monero's own derivation end to end, on keys neither side had seen before. That
is the same grade of evidence that made chains/xrp_crypto_condition.py defensible
(byte-identical agreement with an independent implementation) and it is stronger than
the earlier checks, which were against libsodium for the group law and against ONE
pre-existing address for the encoding.

AND THE CHAIN AGREED TOO, 2026-09-27. `shared_address` IS NO LONGER A PROPOSAL.

`monero_shared_key_verify.py --sweep` ran on the operator's host against the regtest
chain. The shared address was funded by mining to it, and then:

    unlocked in the shared wallet   738741466321372 atomic units
    sweep_all                       1 transaction
    swept                           738723841921372 atomic units
    txid                            f584606948f430bf4835eb399c4e5373a027ee91cfb139ddf8d972bf1f15eade

So an output paid to an address built from two PUBLIC key shares was spent with the
sum of the two PRIVATE shares, by a wallet reconstructed from nothing but those sums.
That is the property a GRC<->XMR swap rests on, and it is measured rather than argued:
the arithmetic (against libsodium and the homomorphism), the encoding (against a real
wallet's address and against generate_from_keys' own derivation) and now the SPEND.

The difference between the two amounts is the transaction fee, which is the ordinary
reason a sweep moves slightly less than the balance and is noted so nobody reads it as
a discrepancy.

WHAT IS STILL NOT TESTED, AND IT IS NOT THIS FILE. The four components of a GRC<->XMR
swap -- adaptor signatures, the ed25519 group law, the cross-curve DLEQ, and this
shared key -- are each tested now. They have NEVER BEEN COMPOSED. There is no protocol
driver: nothing sequences the two legs, nothing joins an adaptor signature on a
Gridcoin transaction to the leak of a Monero key share, and nothing handles the refund
branches or the timelock ordering between them. "Every piece works" and "the swap
works" are different sentences, and docs/dleq_cross_curve_design.md section 6 stage 5
is where that gap is named. Nothing in this file should be read as closing it.

KECCAK-256 IS NOT SHA3-256, AND hashlib HAS ONLY THE SECOND

Monero predates the SHA-3 standard and uses original Keccak padding.
`hashlib.sha3_256(b"")` is `a7ffc6f8...`; Keccak-256 of the empty string is
`c5d24601...`. They are different functions, and reaching for `sha3_256` because
the name is close produces an address with a wrong checksum that every wallet
rejects -- the good failure -- or, in a worse world, a checksum that happens to
validate for a body that is wrong.

So this file uses `Crypto.Hash.keccak` from pycryptodome, newly declared in
requirements.txt. That is a deliberate choice over the ~100 lines of Keccak-f[1600]
this file would otherwise contain: hand-rolling a hash function to avoid a
dependency is the same trade docs/dleq_cross_curve_design.md section 7 refused for
the DLEQ itself, and it refused it in favor of reviewed code other people run. The
empty-string digest above is asserted in the test as a guard that the dependency
is the function this file means.
"""

from __future__ import annotations

from dataclasses import dataclass

from Crypto.Hash import keccak
from modules.ed25519_group import (
    GROUP_ORDER,
    Point,
    is_canonical,
    is_torsion_free,
    scalar_add,
    scalar_base_mul,
)

# Monero's base58 alphabet. Bitcoin's ordering, and it excludes the same four
# ambiguous characters (0, O, I, l) -- but the ENCODING is not Bitcoin's, which is
# the part that catches people. See _decode_block.
MONERO_BASE58_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

FULL_BLOCK_BYTES = 8
FULL_BLOCK_CHARS = 11

# How many base58 characters encode a block of n bytes, for n = 1..8. DERIVED, not
# transcribed: it is ceil(log58(2^(8n))) and the derivation is in the test, which
# recomputes the whole table and asserts it equals this one. Written out here
# because the decoder needs the inverse lookup and a loop would obscure it.
#
#     1 byte  -> 2 chars      5 bytes -> 7 chars
#     2 bytes -> 3 chars      6 bytes -> 9 chars
#     3 bytes -> 5 chars      7 bytes -> 10 chars
#     4 bytes -> 6 chars      8 bytes -> 11 chars
ENCODED_BLOCK_CHARS = (0, 2, 3, 5, 6, 7, 9, 10, 11)

PUBLIC_KEY_BYTES = 32
CHECKSUM_BYTES = 4

# One byte of network/kind prefix, then the public spend key, then the public view
# key. 65 bytes, confirmed by decoding a real stagenet address.
STANDARD_BODY_BYTES = 1 + PUBLIC_KEY_BYTES + PUBLIC_KEY_BYTES


@dataclass(frozen=True)
class NetworkPrefix:
    """One address kind on one network, and the TWO GRADES of evidence for its byte.

    Two booleans rather than one `verified`, because the two things they record are
    different and collapsing them would be rule 17's failure in a struct field:

      from_source   the byte was read out of Monero's own cryptonote_config.h.
                    Authoritative for what the software does, and available for every
                    network without running anything.
      from_address  a real address of this kind, produced by a real wallet, was
                    decoded here and its Keccak checksum reproduced. That is evidence
                    about the whole pipeline -- base58 blocks, body layout, checksum
                    -- and not only about one byte.

    `decode_address` reports both in its refusal when an address matches nothing, so a
    reader debugging an address is told exactly which kind of check is missing rather
    than concluding their address is malformed.
    """

    name: str
    network: str
    byte: int
    from_source: bool
    from_address: bool


# ALL NINE READ OUT OF MONERO'S OWN cryptonote_config.h on release-v0.18, 2026-09-27,
# at the line numbers below. They were previously "as understood" -- written from
# recollection and marked unverified -- and every one of them turned out to match,
# which is worth recording precisely because it might not have:
#
#     mainnet    18 / 19 / 42    cryptonote_config.h:227-229
#     testnet    53 / 54 / 63    cryptonote_config.h:270-272
#     stagenet   24 / 25 / 36    cryptonote_config.h:285-287
#
# AND REGTEST USES THE MAINNET PREFIXES, which is not a guess either:
# `get_config(network_type)` at cryptonote_config.h:321 has
# `case FAKECHAIN: return mainnet;` at line 361. That is why a regtest wallet's
# address decodes here as mainnet/primary, and it is load-bearing for
# monero_shared_key_verify.py, which has to build a shared address with mainnet
# prefixes when the daemon says fakechain.
#
# TWO of the nine additionally have a real address behind them (from_address), which is
# the stronger grade because it exercises the base58 block decoder, the body layout and
# the Keccak checksum together rather than one byte:
#
#     stagenet/primary  the operator's faucet-funded wallet, 537wxk1v...  (byte 24)
#     mainnet/primary   the regtest wallet monero_regtest.py created, 4AFtXcb8...
#                       (byte 18) -- decoded with a verified checksum during the
#                       2026-09-27 run on the operator's host
NETWORK_PREFIXES: tuple[NetworkPrefix, ...] = (
    NetworkPrefix("primary", "stagenet", 24, from_source=True, from_address=True),
    NetworkPrefix("primary", "mainnet", 18, from_source=True, from_address=True),
    NetworkPrefix("integrated", "mainnet", 19, from_source=True, from_address=False),
    NetworkPrefix("subaddress", "mainnet", 42, from_source=True, from_address=False),
    NetworkPrefix("primary", "testnet", 53, from_source=True, from_address=False),
    NetworkPrefix("integrated", "testnet", 54, from_source=True, from_address=False),
    NetworkPrefix("subaddress", "testnet", 63, from_source=True, from_address=False),
    NetworkPrefix("integrated", "stagenet", 25, from_source=True, from_address=False),
    NetworkPrefix("subaddress", "stagenet", 36, from_source=True, from_address=False),
)

_PREFIX_BY_BYTE = {prefix.byte: prefix for prefix in NETWORK_PREFIXES}
_PRIMARY_BY_NETWORK = {
    prefix.network: prefix for prefix in NETWORK_PREFIXES if prefix.name == "primary"
}


class MoneroAddressError(ValueError):
    """A malformed address, a bad checksum, or an address on the wrong network.

    One class for all three because every one of them means "do not send to this",
    and the message says which. A caller that needs to branch on the reason should
    read `decode_address`'s return value on the success path instead -- the network
    is reported there, so "valid but MAINNET" is a normal result and not an error,
    which is what lets a caller refuse it with its own message.
    """


class MoneroKeyError(ValueError):
    """A key share that is not usable: wrong length, non-canonical, or torsion-bearing."""


def keccak256(data: bytes) -> bytes:
    """Keccak-256, the pre-standard padding Monero uses. NOT hashlib.sha3_256.

    Wrapped in one function so there is exactly one place in this tree that
    chooses between the two, and so the choice is named rather than inlined at
    three call sites where a future reader would have to check each one.
    """
    return keccak.new(digest_bits=256, data=data).digest()


def _decode_block(chars: str) -> bytes:
    """One base58 block -> its fixed number of bytes, big-endian.

    MONERO'S BASE58 IS NOT BITCOIN'S, AND THIS FUNCTION IS THE DIFFERENCE.
    Bitcoin base58 treats the whole payload as one big integer, so the output
    length depends on the value and leading zero bytes need separate handling.
    Monero splits the payload into 8-byte blocks, encodes each as its own integer
    into exactly 11 characters, and pads with the alphabet's zero digit -- so
    block boundaries are fixed and a leading zero byte inside a block is carried
    by the padding rather than by a convention.

    The consequence that matters: a Bitcoin base58 decoder run on a Monero address
    produces the wrong bytes, without erroring, for any address with a zero byte
    near a block boundary. It does not fail loudly, which is why the block decode
    is written out here instead of reusing `base58`, a package this repo already
    depends on for the Bitcoin form.
    """
    try:
        size = ENCODED_BLOCK_CHARS.index(len(chars))
    except ValueError:
        raise MoneroAddressError(
            f"a base58 block of {len(chars)} characters is not a valid Monero block "
            f"length; the valid lengths are {ENCODED_BLOCK_CHARS[1:]}"
        ) from None

    value = 0
    for character in chars:
        digit = MONERO_BASE58_ALPHABET.find(character)
        if digit < 0:
            raise MoneroAddressError(
                f"{character!r} is not in Monero's base58 alphabet. Note it omits "
                f"0, O, I and l, and that this is NOT the XRP Ledger alphabet, "
                f"which reorders the same 58 characters"
            )
        value = value * 58 + digit

    if value >= 1 << (8 * size):
        raise MoneroAddressError(
            f"a {len(chars)}-character block decoded to a value too large for its "
            f"{size} bytes -- this is an overlong encoding and a canonical address "
            f"never contains one"
        )
    return value.to_bytes(size, "big")


def _encode_block(chunk: bytes) -> str:
    """The inverse: n bytes -> exactly ENCODED_BLOCK_CHARS[n] characters, zero-padded."""
    width = ENCODED_BLOCK_CHARS[len(chunk)]
    value = int.from_bytes(chunk, "big")
    characters = []
    for _ in range(width):
        value, digit = divmod(value, 58)
        characters.append(MONERO_BASE58_ALPHABET[digit])
    return "".join(reversed(characters))


def base58_encode(payload: bytes) -> str:
    """Monero base58 over 8-byte blocks. The last block may be short."""
    blocks = [
        payload[offset : offset + FULL_BLOCK_BYTES]
        for offset in range(0, len(payload), FULL_BLOCK_BYTES)
    ]
    return "".join(_encode_block(block) for block in blocks)


def base58_decode(text: str) -> bytes:
    """Monero base58 -> bytes. Refuses a final block of an impossible length."""
    if not text:
        raise MoneroAddressError("empty string is not a base58 payload")
    blocks = [
        text[offset : offset + FULL_BLOCK_CHARS]
        for offset in range(0, len(text), FULL_BLOCK_CHARS)
    ]
    return b"".join(_decode_block(block) for block in blocks)


@dataclass(frozen=True)
class MoneroAddress:
    """A decoded address: which network and kind, and the two public keys."""

    address: str
    network: str
    kind: str
    prefix_byte: int
    public_spend_key: bytes
    public_view_key: bytes
    prefix_from_source: bool
    prefix_from_address: bool

    def is_mainnet(self) -> bool:
        return self.network == "mainnet"


def decode_address(address: str) -> MoneroAddress:
    """Decode and CHECK an address: base58, length, prefix, and the Keccak checksum.

    Returning normally does not mean "safe to send to". It means the string is a
    well-formed Monero address and says which network it is on; refusing a mainnet
    address is the caller's decision and `is_mainnet()` is how to make it, because
    a caller that wants to REPORT "this is mainnet" needs the decode to succeed
    first (rule 14: the operator reads the screen, and "MAINNET" is more use than
    "invalid address").
    """
    if not isinstance(address, str):
        raise MoneroAddressError(f"address must be a string, got {type(address).__name__}")

    raw = base58_decode(address.strip())
    if len(raw) < STANDARD_BODY_BYTES + CHECKSUM_BYTES:
        raise MoneroAddressError(
            f"decoded to {len(raw)} bytes, and a standard address is "
            f"{STANDARD_BODY_BYTES + CHECKSUM_BYTES} (1 prefix + 32 spend + 32 view + 4 "
            f"checksum). An integrated address is 8 bytes longer and is not handled here"
        )
    if len(raw) != STANDARD_BODY_BYTES + CHECKSUM_BYTES:
        raise MoneroAddressError(
            f"decoded to {len(raw)} bytes; only the {STANDARD_BODY_BYTES + CHECKSUM_BYTES}-byte "
            f"standard form is handled. An integrated address carries an 8-byte payment ID "
            f"and a swap has no use for one -- the shared address is generated per swap, so "
            f"there is nothing to disambiguate"
        )

    body, checksum = raw[:-CHECKSUM_BYTES], raw[-CHECKSUM_BYTES:]
    computed = keccak256(body)[:CHECKSUM_BYTES]
    if checksum != computed:
        raise MoneroAddressError(
            f"checksum mismatch: the address carries {checksum.hex()} and Keccak-256 of "
            f"its body gives {computed.hex()}. Either a character was mistyped, or the "
            f"address was built with sha3_256 instead of Keccak-256 -- those are "
            f"different functions and Monero uses the second"
        )

    prefix_byte = body[0]
    prefix = _PREFIX_BY_BYTE.get(prefix_byte)
    if prefix is None:
        known = ", ".join(
            f"{candidate.byte}={candidate.network}/{candidate.name}"
            for candidate in NETWORK_PREFIXES
        )
        raise MoneroAddressError(
            f"prefix byte {prefix_byte} is not one this file knows. The checksum VERIFIED, "
            f"so the address is internally consistent and the gap is this table rather than "
            f"your address. All nine bytes here were read out of Monero's own "
            f"cryptonote_config.h: {known}. An integrated address is 8 bytes longer than a "
            f"standard one and is not handled at all, which is the most likely reason to land "
            f"here"
        )

    return MoneroAddress(
        address=address.strip(),
        network=prefix.network,
        kind=prefix.name,
        prefix_byte=prefix_byte,
        public_spend_key=body[1 : 1 + PUBLIC_KEY_BYTES],
        public_view_key=body[1 + PUBLIC_KEY_BYTES :],
        prefix_from_source=prefix.from_source,
        prefix_from_address=prefix.from_address,
    )


def encode_address(network: str, public_spend_key: bytes, public_view_key: bytes) -> str:
    """Build a standard address. `network` is REQUIRED and there is no default.

    No default, on purpose: every other argument in this file can be wrong and
    produce a refusal somewhere, and a defaulted network would silently produce a
    MAINNET address from a test that meant stagenet. The one-word argument is the
    cheapest possible guard against the most expensive possible typo.
    """
    prefix = _PRIMARY_BY_NETWORK.get(network)
    if prefix is None:
        known = ", ".join(sorted(_PRIMARY_BY_NETWORK))
        raise MoneroAddressError(f"unknown network {network!r}; expected one of {known}")
    for name, key in (("spend", public_spend_key), ("view", public_view_key)):
        if len(key) != PUBLIC_KEY_BYTES:
            raise MoneroKeyError(
                f"public {name} key must be {PUBLIC_KEY_BYTES} bytes, got {len(key)}"
            )
        if not is_canonical(key):
            raise MoneroKeyError(
                f"public {name} key is not a canonical ed25519 encoding, so it is not a "
                f"point any wallet will accept"
            )
    body = bytes([prefix.byte]) + public_spend_key + public_view_key
    return base58_encode(body + keccak256(body)[:CHECKSUM_BYTES])


def _checked_share(share: int, name: str) -> int:
    """A private key share must be a non-zero scalar below l, and the value is never quoted.

    Zero is refused separately from out-of-range because a zero share is the one
    value that makes the sum equal the OTHER party's share alone -- so a
    counterparty who can get you to accept zero has the whole key. That is a
    protocol attack rather than a typo, and it deserves its own sentence.
    """
    if not isinstance(share, int):
        raise MoneroKeyError(f"{name} must be an int, got {type(share).__name__}")
    if share == 0:
        raise MoneroKeyError(
            f"{name} is zero. The shared key would then equal the other share alone, so "
            f"one party would hold the whole spend key -- this is refused as a protocol "
            f"violation, not corrected"
        )
    if not 0 < share < GROUP_ORDER:
        # The value is not quoted: it is a spend-key share, and exception text
        # reaches logs and bug reports. A bit length is enough to fix the call.
        raise MoneroKeyError(
            f"{name} must be in [1, l) where l is the ed25519 group order; this one is "
            f"{share.bit_length()} bits and {'negative' if share < 0 else 'at or above l'}"
        )
    return share


def shared_private_spend_key(share_a: int, share_b: int) -> int:
    """s = s_a + s_b mod l -- the key that spends the swapped XMR.

    Neither party may learn this before the swap commits; each holds one share,
    and the adaptor signature on the Gridcoin leg is what leaks the other. This
    function exists for the END of a swap, when one share has been recovered, and
    for tests. It is NOT how the address is built: that is `shared_address`, which
    needs only the public halves, and keeping the two apart is what lets the
    address be computed by a party who holds one share.
    """
    return scalar_add(_checked_share(share_a, "share_a"), _checked_share(share_b, "share_b"))


def _checked_public_share(key: bytes, name: str) -> Point:
    """A public share must be canonical, on the curve, and torsion-free.

    The torsion check is the one that would be tempting to skip and must not be.
    A share with a small-order component lets a counterparty submit several
    distinct encodings that sum to the same nominal key while disagreeing about
    which point was committed to -- the same class of attack the ed25519
    canonicity rules exist for. modules/ed25519_group.is_torsion_free is stricter
    than some libsodium builds' own predicate on exactly this property; see
    tests/test_ed25519_group.py, where an older libsodium accepts an order-2
    component that this one rejects.
    """
    if len(key) != PUBLIC_KEY_BYTES:
        raise MoneroKeyError(f"{name} must be {PUBLIC_KEY_BYTES} bytes, got {len(key)}")
    if not is_canonical(key):
        raise MoneroKeyError(f"{name} is not a canonical ed25519 encoding")
    point = Point.decompress(key)
    if point.is_identity():
        raise MoneroKeyError(
            f"{name} is the identity, which contributes nothing -- the shared key would "
            f"be the other party's alone"
        )
    if not is_torsion_free(point):
        raise MoneroKeyError(
            f"{name} has a small-order torsion component, so several distinct encodings "
            f"agree with it and the share does not pin one point. Refused"
        )
    return point


def shared_public_key(share_a: bytes, share_b: bytes) -> bytes:
    """S = S_a + S_b, as a compressed ed25519 encoding. Both shares fully checked.

    Point addition, and it commutes -- so both parties compute the same byte
    string regardless of which share they call theirs. A test asserts the
    commutativity rather than leaving it to the reader, because the whole protocol
    rests on the two sides agreeing on one address.
    """
    return _checked_public_share(share_a, "share_a").add(
        _checked_public_share(share_b, "share_b")
    ).compress()


def public_key_for_share(share: int) -> bytes:
    """The public half of one private share: share * B, compressed."""
    return scalar_base_mul(_checked_share(share, "share")).compress()


def shared_address(
    network: str,
    spend_share_a: bytes,
    spend_share_b: bytes,
    view_share_a: bytes,
    view_share_b: bytes,
) -> str:
    """The address a GRC<->XMR swap locks its Monero to. A PROPOSAL, not a tested fix.

    Both the spend and the view key are summed. Summing the VIEW key too is what
    lets each party watch for the lock without either being able to spend, and it
    is why there are four arguments rather than two: a shared spend key with one
    party's view key would let that party alone see the funds arrive.

    NOT TESTED AGAINST A CHAIN (rule 16). The arithmetic here is checked -- point
    addition against libsodium, the encoding against a real wallet-generated
    stagenet address -- but that XMR sent to the result is spendable with
    `shared_private_spend_key` of the corresponding private shares has never been
    demonstrated, because this container cannot reach a stagenet
    (docs/monero_stagenet_funding.md). Until it has been, this is a proposal.

    The check that WILL settle it, when a daemon is reachable, is one call:
    monero-wallet-rpc's `validate_address` on the output, then a transfer to it and
    a sweep out with the summed key. `chains/monero.py` already has the first.
    """
    return encode_address(
        network,
        shared_public_key(spend_share_a, spend_share_b),
        shared_public_key(view_share_a, view_share_b),
    )


__all__ = [
    "CHECKSUM_BYTES",
    "ENCODED_BLOCK_CHARS",
    "MONERO_BASE58_ALPHABET",
    "NETWORK_PREFIXES",
    "STANDARD_BODY_BYTES",
    "MoneroAddress",
    "MoneroAddressError",
    "MoneroKeyError",
    "NetworkPrefix",
    "base58_decode",
    "base58_encode",
    "decode_address",
    "encode_address",
    "keccak256",
    "public_key_for_share",
    "shared_address",
    "shared_private_spend_key",
    "shared_public_key",
]
