#!/usr/bin/env python3
"""Stand up a Monero REGTEST chain, mine to a wallet, make one transfer. No faucet, no network.

Role: file (operator entry point, at the project root per CLAUDE.md rule 10)
Reads: the monerod and monero-wallet-rpc binaries on PATH, and the regtest data
       directory it creates under --data-dir
Writes: a private regtest blockchain and a new wallet, both under --data-dir
        (default ~/xmr-regtest), plus two pid files there. Nothing in the repo,
        nothing in ~/.bitmonero, nothing in the swap database.
Can move funds: ONLY on a private regtest chain it created itself, whose coins
       are generated by this script and exist nowhere else. It refuses to run
       against any other network -- see REFUSALS below, which is the most
       important section in this file.
Mainnet-safe: yes, and it is made safe by construction rather than by care.
       `generateblocks` is gated inside monerod itself:
       src/rpc/core_rpc_server.cpp:1956 returns
       CORE_RPC_ERROR_CODE_REGTEST_REQUIRED unless the nettype is FAKECHAIN, and
       regtest is its own nettype rather than a mode over another one. So the
       central operation here CANNOT reach stagenet or mainnet even if every
       check below were removed.
Live-safe: yes. It touches no swap database, no live wallet and no configured RPC.

WHY THIS EXISTS: THE FAUCET WAS THE CRITICAL PATH AND IT SHOULD NOT HAVE BEEN

Ten field names in chains/monero_transfers.py -- `txid`, `amount`, `address`,
`amounts`, `subaddr_index`, `confirmations`, `type`, `unlock_time`, `locked`,
`double_spend_seen` -- are the only unconfirmed part of the Monero wire format,
and no unit test can check them: a unit test seeds the same shape it asserts.
monero_chain_check.py is the experiment that can, and it needs one incoming
transfer to look at.

For weeks that meant a stagenet faucet. On 2026-09-27 the only responsive faucet
answered "you have reached request limit, please come tomorrow", and
monero_chain_check.py against the operator's stagenet wallet reported 0.0 XMR and
exited 3 (inconclusive) with all ten names marked unconfirmed.

THE FIELD NAMES ARE A PROPERTY OF THE SOFTWARE, NOT OF THE NETWORK. The same
monero-wallet-rpc binary emits the same keys on regtest as on stagenet. So a
regtest transfer confirms them exactly as well, and it takes seconds.

What regtest does NOT replace: a rehearsal against a network with real peers,
real propagation delay and real reorgs. That still wants stagenet. This removes
the faucet from the critical path; it does not make stagenet pointless.

REFUSALS, AND WHY EACH ONE IS HERE

  no --run                  prints the plan and exits. Starting two daemons is
                            not something a bare invocation should do.
  --data-dir inside the     refused. A blockchain under the checkout would be
  repository                gitignored-or-committed, and both are wrong.
  ~/.bitmonero as the       refused by name. That is where the REAL stagenet and
  data dir                  mainnet chains live, and pointing a regtest daemon
                            at them is the one mistake here that could cost
                            something.
  a daemon already on the   refused rather than reused. A daemon this script did
  chosen RPC port           not start is a daemon whose nettype it did not
                            choose, and "probably regtest" is not good enough
                            when the next call mines blocks.
  nettype not FAKECHAIN     refused after asking the daemon, before any mining.
                            get_info reports `nettype`, and this compares it.

EVERY SPAWN HAS A REAPER, NAMED HERE (rule 13)

Two processes: monerod and monero-wallet-rpc. Both get a pid file in the data
directory, both are terminated by `--stop`, and `--stop` asserts their ABSENCE
rather than the exit code of a kill. The same script that starts them is the
script that stops them, which is rule 13's "a spawn and its reap are one change"
at the smallest scale it can be applied.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "swap_terminal"))

from chains.monero_keys import MoneroAddressError, decode_address
from step_console import Console

# A coinbase output is locked for 60 confirmations on Monero. 80 blocks leaves
# twenty of margin and still takes seconds at difficulty 1, which is why the
# default is not 61: a run that mines exactly to the boundary fails for a reason
# that reads like a bug in the wallet.
COINBASE_UNLOCK_BLOCKS = 60
DEFAULT_BLOCKS = 80

# Ports deliberately NOT Monero's defaults for mainnet (18081) or stagenet
# (38081). A regtest daemon on 18081 is one typo away from a wallet that meant
# mainnet, and the whole point of this file is that such a typo cannot matter.
DEFAULT_DAEMON_PORT = 28081
DEFAULT_P2P_PORT = 28080
DEFAULT_WALLET_PORT = 28083

# monerod reports its network in get_info as `nettype`, and regtest is spelled
# "fakechain" there -- the same FAKECHAIN the generateblocks gate compares
# against in src/rpc/core_rpc_server.cpp. Asserted rather than assumed.
REGTEST_NETTYPE = "fakechain"

# A standard Monero address is 95 base58 characters and a txid is 64 hex. Named
# rather than inlined because ruff's PLR2004 is right that a bare 95 in a
# comparison says nothing -- and because chains/monero_keys.py already owns the
# structure behind the first one.
MONERO_ADDRESS_CHARS = 95
TXID_HEX_CHARS = 64

WALLET_NAME = "regwallet"
# An empty password is correct for a throwaway chain and wrong everywhere else.
# It is spelled out rather than defaulted so that nothing here can be copied to a
# wallet that matters without the copier noticing.
WALLET_PASSWORD = ""

PID_FILES = {"monerod": "monerod.pid", "wallet": "monero-wallet-rpc.pid"}


class RegtestError(RuntimeError):
    """A refusal, or a daemon that did not do what it was asked."""


@dataclass(frozen=True)
class Daemon:
    """One spawned process: what to call it, where it listens, where it logs, and the
    handle to ask whether it is still alive.

    These four always travel together -- every caller that has one has all four --
    and ruff's PLR0913 on the seven-argument wait_for_rpc was right that they wanted
    to be one thing. Rule 12: "the fix is to extract the decision so it can be
    called with seeded inputs, not to raise the ceiling." The `process` handle is
    what makes the difference between waiting for a daemon and waiting for a corpse.
    """

    label: str
    port: int
    log_path: Path
    process: subprocess.Popen


def rpc(port: int, method: str, params: dict | None = None, timeout: int = 60) -> dict:
    """One JSON-RPC call to a local monerod or monero-wallet-rpc.

    Errors arrive as HTTP 200 with an `error` member, so the error is read BEFORE
    anything else -- the same shape, and the same trap, as
    swap_terminal/modules/htlc_rpc.py's rpc_result(): calling raise_for_status()
    first discards the reason.
    """
    body = json.dumps(
        {"jsonrpc": "2.0", "id": "0", "method": method, "params": params or {}}
    ).encode()
    # The suppression on the urlopen below is a CHECKED claim (rule 12), and what
    # was checked is this: S310 warns that urlopen follows whatever scheme a URL
    # names, including file:// and custom handlers. Here the scheme and host are
    # literal -- "http://127.0.0.1" -- and the only interpolation is an integer port
    # from argparse, so no caller can choose either. Ruff does not flag the Request
    # constructor, only the call that performs the fetch, so there is exactly one.
    request = urllib.request.Request(
        f"http://127.0.0.1:{port}/json_rpc",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
            payload = json.loads(response.read())
    except urllib.error.URLError as error:
        raise RegtestError(f"{method} on port {port}: {error}") from error
    if "error" in payload:
        raise RegtestError(f"{method} on port {port}: {payload['error']}")
    result = payload.get("result")
    if not isinstance(result, dict):
        raise RegtestError(f"{method} on port {port}: no `result` object in the reply")
    return result


def port_is_open(port: int) -> bool:
    """Is something already listening? Checked by TRYING it, not by parsing netstat."""
    with socket.socket() as probe:
        probe.settimeout(1.0)
        return probe.connect_ex(("127.0.0.1", port)) == 0


def refuse_dangerous_data_dir(data_dir: Path) -> None:
    """The two refusals that could cost something, checked before anything starts.

    ~/.bitmonero holds the real stagenet and mainnet chains. A regtest daemon
    pointed there would create a `regtest` subdirectory beside them, which is
    probably harmless and is absolutely not worth finding out. And a blockchain
    inside the repository checkout is either committed or gitignored, and both are
    wrong.
    """
    resolved = data_dir.expanduser().resolve()
    bitmonero = (Path.home() / ".bitmonero").resolve()
    if resolved == bitmonero or bitmonero in resolved.parents:
        raise RegtestError(
            f"refusing --data-dir {resolved}: that is inside ~/.bitmonero, where the REAL "
            f"stagenet and mainnet chains live. Pick a directory of its own"
        )
    repository = Path(__file__).resolve().parent
    if resolved == repository or repository in resolved.parents:
        raise RegtestError(
            f"refusing --data-dir {resolved}: a blockchain inside the checkout would have to "
            f"be committed or gitignored, and both are wrong. Pick a directory outside it"
        )


def write_pid(data_dir: Path, which: str, pid: int) -> None:
    """A pid FILE, not a pgrep pattern. Rule 13: a pattern matches what the command
    line happens to look like today, and renaming a script silently orphans it."""
    (data_dir / PID_FILES[which]).write_text(f"{pid}\n")


def process_is_alive(pid: int) -> bool:
    """Is this pid a RUNNING process? A zombie is not, and os.kill(pid, 0) says it is.

    THIS DISTINCTION IS A DEFECT A TEST FOUND, and it is the kind rule 13 is about.
    A killed child whose parent has not called wait() stays in the process table as
    a zombie, and `os.kill(pid, 0)` on a zombie SUCCEEDS -- the pid still exists. So
    the obvious liveness check reports "STILL RUNNING" for a process that is dead
    and merely unreaped, which is exactly the false alarm that teaches an operator
    to stop believing the stop.

    It did not bite in normal use only by luck of process topology: `--run` and
    `--stop` are separate invocations, so by the time `--stop` kills the daemons
    their original parent has exited and init has reaped them. A caller that did
    both in one process -- which tests/test_monero_regtest.py does, deliberately --
    would have seen the false failure. Relying on that topology rather than fixing
    it would be the "I could not find a caller" reasoning rule 2 refuses.

    /proc/<pid>/stat's third field is the state character; 'Z' is a zombie and 'X'
    is dead. Linux-specific, and this repo is Linux-only in the places that matter
    (the daemons, warbot.sh's pgrep patterns). If /proc is unreadable the answer
    falls back to os.kill, which is the conservative direction: it reports alive.
    """
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        # It exists and belongs to somebody else. Alive, and not ours to kill.
        return True
    try:
        stat = Path(f"/proc/{pid}/stat").read_text()
    except OSError:
        return True
    # The comm field is parenthesised and may itself contain spaces and parens, so
    # the state is the first field AFTER the last ')' rather than split()[2].
    tail = stat.rpartition(")")[2].split()
    return not (tail and tail[0] in {"Z", "X"})


def stop_one(console: Console, data_dir: Path, which: str) -> bool:
    """Terminate one recorded process and ASSERT IT IS GONE.

    Rule 13: "a stop that cannot prove it worked is not a stop. Follow it with a
    check that the process is gone, and make the absence the assertion -- not the
    exit code of the kill." process_is_alive() is what makes that assertion
    trustworthy; see its docstring for the zombie case that made it necessary.
    """
    pid_path = data_dir / PID_FILES[which]
    if not pid_path.is_file():
        return console.check(f"{which} stopped", "no pid file", "gone or never started", True)
    try:
        pid = int(pid_path.read_text().strip())
    except ValueError:
        return console.check(f"{which} stopped", "unreadable pid file", "an integer", False)

    # SIGTERM twice with a widening wait, then SIGKILL. The escalation exists
    # because a daemon blocked writing into a full pipe will not act on a SIGTERM
    # handler, and a stop that gives up politely is not a stop.
    for attempt, sig in ((1, signal.SIGTERM), (2, signal.SIGTERM), (3, signal.SIGKILL)):
        if not process_is_alive(pid):
            break
        try:
            os.kill(pid, sig)
        except ProcessLookupError:
            break
        for _ in range(20 * attempt):
            time.sleep(0.25)
            if not process_is_alive(pid):
                break
        if not process_is_alive(pid):
            break

    if process_is_alive(pid):
        return console.check(f"{which} stopped", f"pid {pid} is STILL RUNNING", "absence", False)
    pid_path.unlink(missing_ok=True)
    return console.check(f"{which} stopped", f"pid {pid} is gone", "absence", True)


def log_tail(log_path: Path, lines: int = 25) -> str:
    """The last lines of a daemon's log, for an error message to CARRY rather than
    point at.

    "Check the log in the data directory" is not a diagnostic -- it is homework, and
    it is what this function replaces. Rule 14: state what the number means next to
    the number; the same applies to a failure and its reason.
    """
    try:
        text = log_path.read_text(errors="replace").strip()
    except OSError as error:
        return f"({log_path} could not be read: {error})"
    if not text:
        return f"({log_path} is empty -- the process wrote nothing at all)"
    return "\n".join(f"          | {line}" for line in text.splitlines()[-lines:])


def wait_for_rpc(console: Console, daemon: Daemon, method: str, seconds: int = 60) -> dict:
    """Poll until the daemon answers -- and STOP THE MOMENT IT DIES.

    THE SECOND HALF IS A DEFECT THIS FUNCTION USED TO HAVE. It polled for the full
    sixty seconds regardless, so a wallet that rejected its own command line and
    exited in 40ms produced forty identical progress lines and then "did not answer
    within 60s". That message is true and useless: it describes the symptom of a
    process that was never running, and it is two steps from the cause. Worse, it
    made the operator wait a minute to be told nothing.

    Now the child's exit status is checked every pass, and an exit is reported
    immediately WITH the tail of its log. Rule 14's "announce before, not only
    after" has a corollary: when the thing being waited for is already dead, say so
    instead of continuing to announce waiting.

    The progress lines stay, because a blinking cursor is indistinguishable from a
    hang and the operator's response to a hang is Ctrl-C.
    """
    started = time.monotonic()
    attempt = 0
    while time.monotonic() - started < seconds:
        attempt += 1
        exit_code = daemon.process.poll()
        if exit_code is not None:
            raise RegtestError(
                f"{daemon.label} EXITED with status {exit_code} after "
                f"{time.monotonic() - started:.1f}s -- it never bound port {daemon.port}. Its "
                f"log says:\n{log_tail(daemon.log_path)}"
            )
        try:
            return rpc(daemon.port, method, timeout=5)
        except RegtestError:
            elapsed = time.monotonic() - started
            console.say(
                f"waiting for {daemon.label} on {daemon.port}: attempt {attempt}, "
                f"{elapsed:.1f}s elapsed"
            )
            time.sleep(1.5)
    raise RegtestError(
        f"{daemon.label} is still running but did not answer {method} on port {daemon.port} "
        f"within {seconds}s. Its log says:\n{log_tail(daemon.log_path)}"
    )


def spawn(command: list[str], log_path: Path) -> subprocess.Popen:
    """Start a daemon with its output on disk, so a failure to start is readable.

    Reaped by stop_one() via the pid file written by the caller -- named here
    because rule 13 asks for the reaper to be named AT THE SPAWN SITE.
    """
    handle = log_path.open("ab")
    return subprocess.Popen(  # noqa: S603  a fixed argv this file built from its own arguments
        command, stdout=handle, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Stand up a Monero regtest chain and produce one incoming transfer."
    )
    parser.add_argument("--run", action="store_true", help="actually start the daemons")
    parser.add_argument("--stop", action="store_true", help="terminate what a previous --run started")
    parser.add_argument("--data-dir", default=str(Path.home() / "xmr-regtest"))
    parser.add_argument("--blocks", type=int, default=DEFAULT_BLOCKS)
    parser.add_argument("--daemon-port", type=int, default=DEFAULT_DAEMON_PORT)
    parser.add_argument("--p2p-port", type=int, default=DEFAULT_P2P_PORT)
    parser.add_argument("--wallet-port", type=int, default=DEFAULT_WALLET_PORT)
    parser.add_argument("--monerod", default="monerod")
    parser.add_argument("--wallet-rpc", default="monero-wallet-rpc")
    return parser


def print_plan(console: Console, args: argparse.Namespace) -> None:
    """What --run would do, printed instead of done. Rule 14: announce before acting,
    and a bare invocation that starts two daemons has announced nothing."""
    console.banner("PLAN ONLY -- nothing started. Add --run to do this.")
    console.say(f"data dir      {args.data_dir}  (created; separate from ~/.bitmonero)")
    console.say(f"monerod       --regtest --offline --fixed-difficulty 1 on rpc {args.daemon_port}")
    console.say(f"blocks        {args.blocks} mined to a new wallet ({COINBASE_UNLOCK_BLOCKS} unlock + margin)")
    console.say(f"wallet rpc    {args.wallet_rpc} on {args.wallet_port}, then one self-transfer")
    console.say("then          python3 monero_chain_check.py --host 127.0.0.1 "
                f"--port {args.wallet_port}")
    console.say("")
    console.say("WHY THIS IS SAFE: generateblocks is refused by monerod itself unless")
    console.say("the nettype is FAKECHAIN (src/rpc/core_rpc_server.cpp:1956), and regtest")
    console.say("is its own nettype -- so it cannot reach stagenet or mainnet at all.")


def start_daemon(console: Console, args: argparse.Namespace, data_dir: Path) -> None:
    """Step 2: monerod on a private chain, then CONFIRM its nettype before mining."""
    if port_is_open(args.daemon_port):
        raise RegtestError(
            f"something is already listening on {args.daemon_port}. Refusing to reuse it: a "
            f"daemon this script did not start is a daemon whose nettype it did not choose, and "
            f"the next step mines blocks. Run --stop first, or pick another --daemon-port"
        )
    command = [
        args.monerod,
        "--regtest",
        "--offline",
        "--fixed-difficulty", "1",
        "--data-dir", str(data_dir),
        "--rpc-bind-port", str(args.daemon_port),
        "--p2p-bind-port", str(args.p2p_port),
        "--non-interactive",
        "--log-level", "0",
    ]
    console.say(" ".join(command))
    log_path = data_dir / "monerod.log"
    process = spawn(command, log_path)
    write_pid(data_dir, "monerod", process.pid)
    console.say(f"monerod pid {process.pid}, reaped by `--stop` via {PID_FILES['monerod']}")

    info = wait_for_rpc(
        console, Daemon("monerod", args.daemon_port, log_path, process), "get_info"
    )
    nettype = str(info.get("nettype", "(not reported)"))
    console.check("monerod nettype", nettype, REGTEST_NETTYPE, nettype == REGTEST_NETTYPE)
    if nettype != REGTEST_NETTYPE:
        raise RegtestError(
            f"the daemon says nettype={nettype!r}, not {REGTEST_NETTYPE!r}. Refusing to mine. "
            f"This is the check that stands between a mistyped flag and a real network"
        )
    console.check("monerod height at start", info.get("height"), "1 on a fresh chain",
                  isinstance(info.get("height"), int))


def create_wallet(console: Console, args: argparse.Namespace, data_dir: Path) -> str:
    """Step 3: a wallet on this chain, via monero-wallet-rpc's own create_wallet.

    Done over RPC rather than with monero-wallet-cli because the CLI is interactive
    and an interactive prompt in a pasteable block is rule 14's blinking cursor. The
    wallet RPC is started here in --wallet-dir mode, which is the mode that HAS
    create_wallet and open_wallet; it is the same process used for the rest of the run.
    """
    if port_is_open(args.wallet_port):
        raise RegtestError(
            f"something is already listening on {args.wallet_port}. Run --stop first, or pick "
            f"another --wallet-port"
        )
    # NO --regtest HERE, AND THAT WAS A REAL BUG. monero-wallet-rpc does not have
    # that option: `regtest` appears ZERO times in wallet_rpc_server.cpp,
    # wallet2.cpp and simplewallet.cpp (grepped against release-v0.18 on
    # 2026-09-27). Passing it made the wallet reject its own command line and exit
    # instantly, so this script then polled a dead process for sixty seconds and
    # reported a timeout -- a symptom two steps removed from the cause.
    #
    # The authority for this argv is Monero's OWN functional test harness,
    # tests/functional_tests/functional_tests_rpc.py, which starts a wallet against
    # exactly this kind of regtest daemon:
    #
    #   monerod_base = [... "--regtest", "--fixed-difficulty", ...]
    #   wallet_base  = ["monero-wallet-rpc", "--wallet-dir", ..., "--rpc-bind-port",
    #                   ..., "--disable-rpc-login", "--rpc-ssl", "disabled",
    #                   "--daemon-ssl", "disabled", "--log-level", "1",
    #                   "--allow-mismatched-daemon-version"]
    #
    # The daemon gets the nettype flag; the wallet gets none. A regtest chain uses
    # mainnet address prefixes, which is why the wallet needs no nettype at all and
    # why the address printed below decodes as mainnet/primary -- expected, not a
    # fault, and step 3 reports it rather than asserting a guess.
    #
    # --allow-mismatched-daemon-version is carried over from that harness for the
    # same reason it is there: a regtest daemon's version handshake need not match,
    # and refusing to talk to it is not a safety property on a private chain.
    command = [
        args.wallet_rpc,
        "--trusted-daemon",
        "--daemon-address", f"127.0.0.1:{args.daemon_port}",
        "--wallet-dir", str(data_dir),
        "--rpc-bind-port", str(args.wallet_port),
        "--disable-rpc-login",
        "--rpc-ssl", "disabled",
        "--daemon-ssl", "disabled",
        "--allow-mismatched-daemon-version",
        "--log-level", "1",
    ]
    console.say(" ".join(command))
    log_path = data_dir / "monero-wallet-rpc.log"
    process = spawn(command, log_path)
    write_pid(data_dir, "wallet", process.pid)
    console.say(f"wallet rpc pid {process.pid}, reaped by `--stop` via {PID_FILES['wallet']}")

    wait_for_rpc(
        console,
        Daemon("monero-wallet-rpc", args.wallet_port, log_path, process),
        "get_version",
    )

    existing = data_dir / WALLET_NAME
    if existing.is_file():
        console.say(f"{WALLET_NAME} already exists in the data dir; opening it")
        rpc(args.wallet_port, "open_wallet", {"filename": WALLET_NAME, "password": WALLET_PASSWORD})
    else:
        rpc(args.wallet_port, "create_wallet",
            {"filename": WALLET_NAME, "password": WALLET_PASSWORD, "language": "English"})
        console.say(f"created {WALLET_NAME}")

    address = str(rpc(args.wallet_port, "get_address", {"account_index": 0})["address"])
    console.check("wallet primary address", f"{address[:12]}...{address[-6:]}",
                  f"{MONERO_ADDRESS_CHARS} base58 characters",
                  len(address) == MONERO_ADDRESS_CHARS)

    # Decode it with this repo's own decoder, and REPORT rather than assert. Which
    # network byte monerod uses on regtest is not something this session has
    # established (chains/monero_keys.NETWORK_PREFIXES marks stagenet/primary as the
    # only verified entry), so a refusal here would be new information about the
    # prefix table rather than a fault in the wallet. Printing it is how that
    # information gets out; failing on it would be asserting a guess.
    try:
        decoded = decode_address(address)
        console.say(f"chains/monero_keys decodes it as {decoded.network}/{decoded.kind} "
                    f"(prefix byte {decoded.prefix_byte}, checksum verified)")
    except MoneroAddressError as error:
        console.say(f"chains/monero_keys could not decode it: {error}")
        console.say("NOT a failure of this run -- it means regtest uses a prefix byte that")
        console.say("NETWORK_PREFIXES does not list yet. Worth adding, with this as the source.")
    return address


def mine(console: Console, args: argparse.Namespace, address: str) -> int:
    """Step 4: generateblocks to the wallet. THE call that regtest gates.

    src/rpc/core_rpc_server.cpp:1956 returns CORE_RPC_ERROR_CODE_REGTEST_REQUIRED
    unless the nettype is FAKECHAIN, so this line cannot execute against stagenet or
    mainnet. Everything else in this file is belt; this is the braces, and it is in
    monerod rather than here.
    """
    result = rpc(args.daemon_port, "generateblocks",
                 {"amount_of_blocks": args.blocks, "wallet_address": address},
                 timeout=300)
    height = int(result.get("height", 0))
    console.check("height after mining", height, f"at least {args.blocks}", height >= args.blocks)
    console.say(f"{args.blocks} blocks mined; a coinbase unlocks after "
                f"{COINBASE_UNLOCK_BLOCKS}, so {args.blocks - COINBASE_UNLOCK_BLOCKS} are spendable")
    return height


def wait_for_unlocked_balance(console: Console, args: argparse.Namespace, seconds: int = 180) -> int:
    """Step 5: refresh until something is SPENDABLE, not merely present.

    The distinction is the point: `balance` counts locked coinbase outputs and
    `unlocked_balance` does not, so a transfer attempted on the first is refused for
    a reason that reads like a bug. Progress is printed every poll because this is
    the step that can legitimately take a minute.
    """
    started = time.monotonic()
    attempt = 0
    while time.monotonic() - started < seconds:
        attempt += 1
        rpc(args.wallet_port, "refresh")
        balance = rpc(args.wallet_port, "get_balance", {"account_index": 0})
        total = int(balance.get("balance", 0))
        unlocked = int(balance.get("unlocked_balance", 0))
        console.say(f"refresh {attempt}: balance={total} unlocked={unlocked} atomic units "
                    f"({time.monotonic() - started:.1f}s)")
        if unlocked > 0:
            console.check("unlocked balance", unlocked, "greater than 0", True)
            return unlocked
        time.sleep(2.0)
    raise RegtestError(
        f"no UNLOCKED balance after {seconds}s. `balance` may be non-zero while every output is "
        f"still a locked coinbase -- mine more blocks with --blocks"
    )


def make_one_transfer(
    console: Console, args: argparse.Namespace, unlocked: int, miner_address: str
) -> str:
    """Step 6: an ordinary transfer to a second address in the same wallet.

    THIS IS THE STEP THE WHOLE FILE EXISTS FOR, and the reason it is a transfer
    rather than the mining is exact: a coinbase output does NOT appear in
    get_transfers' `in` array. Only a real transfer does, and `in` is where the ten
    field names live. Mining alone would leave monero_chain_check.py reporting the
    same "no `in` key" it reports against an empty stagenet wallet.

    Paying ourselves is deliberate: it needs no second wallet, and the receiving
    subaddress makes `subaddr_index` non-trivial rather than always {0,0}.
    """
    created = rpc(args.wallet_port, "create_address",
                  {"account_index": 0, "label": "regtest-deposit-target"})
    destination = str(created["address"])
    console.say(f"created subaddress at index {created.get('address_index')} to receive")

    # A tenth of what is unlocked, so the fee cannot make the transfer unaffordable.
    amount = max(1, unlocked // 10)
    sent = rpc(args.wallet_port, "transfer",
               {"destinations": [{"amount": amount, "address": destination}],
                "account_index": 0, "get_tx_key": True},
               timeout=180)
    txid = str(sent.get("tx_hash", ""))
    console.check("transfer tx_hash", txid[:16] + "..." if txid else None,
                  f"{TXID_HEX_CHARS} hex characters", len(txid) == TXID_HEX_CHARS)
    console.say(f"sent {amount} atomic units to index {created.get('address_index')}")

    # Two more blocks so the transfer confirms -- an unconfirmed transfer has
    # confirmations=0 and `locked` true, which is a weaker thing to confirm the field
    # names against than a settled one.
    #
    # MINED TO THE PRIMARY ADDRESS, NOT THE SUBADDRESS, AND THAT WAS A BUG. The first
    # version passed `destination` here, which is the subaddress created just above to
    # RECEIVE the transfer, and monerod answered:
    #
    #     code -12  "Mining to subaddress is not supported yet"
    #
    # measured on the operator's host 2026-09-27, after every earlier step had passed.
    # The miner address and the payee address are different roles and the first version
    # conflated them because the same variable was in scope. Nothing about the transfer
    # needed the blocks to be mined anywhere in particular -- they exist only to bury
    # it -- so the primary address is both correct and arbitrary, which is exactly why
    # reusing `destination` looked harmless.
    rpc(args.daemon_port, "generateblocks",
        {"amount_of_blocks": 2, "wallet_address": miner_address}, timeout=120)
    rpc(args.wallet_port, "refresh")

    transfers = rpc(args.wallet_port, "get_transfers", {"in": True, "account_index": 0})
    incoming = transfers.get("in") or []
    console.check("get_transfers `in` entries", len(incoming), "at least 1", len(incoming) >= 1)
    if incoming:
        present = sorted(incoming[0].keys())
        console.say(f"fields on the first incoming transfer: {', '.join(present)}")
    return txid


def run(console: Console, args: argparse.Namespace) -> int:
    data_dir = Path(args.data_dir).expanduser()
    refuse_dangerous_data_dir(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)

    console.banner(f"monero regtest -- private chain in {data_dir}, no network, no faucet")
    console.say("generateblocks is gated to nettype FAKECHAIN inside monerod itself")
    console.say("(src/rpc/core_rpc_server.cpp:1956), so this cannot touch stagenet or mainnet")

    console.step(1, "check the binaries")
    for label, path in (("monerod", args.monerod), ("monero-wallet-rpc", args.wallet_rpc)):
        try:
            version = subprocess.run(  # noqa: S603  a path from argparse, no shell, --version only
                [path, "--version"], capture_output=True, text=True, timeout=30, check=False
            ).stdout.strip().splitlines()
            console.check(f"{label} binary", version[0] if version else None, "a version line",
                          bool(version))
        except (OSError, subprocess.SubprocessError) as error:
            console.check(f"{label} binary", f"{type(error).__name__}: {error}",
                          "a version line", False)
            console.say(
                f"{path!r} did not answer --version. Install Monero's CLI tools, or pass "
                f"--monerod / --wallet-rpc with an explicit path"
            )
            return console.summary()

    console.step(2, "start monerod on a private regtest chain")
    start_daemon(console, args, data_dir)

    console.step(3, "start monero-wallet-rpc and create a wallet on that chain")
    address = create_wallet(console, args, data_dir)

    console.step(4, f"mine {args.blocks} blocks to that wallet")
    mine(console, args, address)

    console.step(5, "refresh until a coinbase output has UNLOCKED")
    unlocked = wait_for_unlocked_balance(console, args)

    console.step(6, "make ONE ordinary transfer -- a coinbase does not appear in `in`")
    make_one_transfer(console, args, unlocked, address)

    console.step(7, "what to run next")
    console.say(f"python3 monero_chain_check.py --host 127.0.0.1 --port {args.wallet_port}")
    console.say("that is the experiment: it reports which of the ten transfer field names")
    console.say("a real wallet actually used, and exits 3 if it still cannot tell")
    console.say("")
    console.say(f"when finished:  python3 monero_regtest.py --stop --data-dir {data_dir}")
    console.say("the daemons stay up on purpose -- monero_chain_check.py needs the wallet rpc")

    return console.summary()


def main() -> int:
    args = build_parser().parse_args()
    console = Console(total_steps=7)

    if args.stop:
        data_dir = Path(args.data_dir).expanduser()
        console.banner(f"stopping what --run started in {data_dir}")
        console.step(1, "terminate both daemons and assert their ABSENCE")
        for which in ("wallet", "monerod"):
            stop_one(console, data_dir, which)
        console.say(f"the chain and wallet are left in place; delete {data_dir} to reclaim it")
        return console.summary()

    if not args.run:
        print_plan(console, args)
        return 0

    try:
        return run(console, args)
    except RegtestError as error:
        console.check("run", f"{error}", "no refusal", False)
        console.say("")
        console.say("the daemons may still be running. Stop them with:")
        console.say(f"  python3 monero_regtest.py --stop --data-dir {args.data_dir}")
        return console.summary()


if __name__ == "__main__":
    sys.exit(main())
