"""Monero address encoding and the shared 2-of-2 spend key, against a real address.

Role: test (read-only)
Reads: nothing on disk; the stagenet address below is embedded
Writes: nothing
Can move funds: no
Mainnet-safe: yes
Live-safe: yes

WHY ONE REAL ADDRESS IS WORTH MORE THAN A HUNDRED SYNTHETIC ONES

Every synthetic case in this file is checked by the same code that produced it, so
a round trip through a wrong-but-consistent encoder passes. STAGENET_ADDRESS was
generated by a real Monero wallet on 2026-09-27 and is bytes this repo did not
produce: decoding it exercises the base58 block decoder, the block-size table, the
body layout, the network byte AND the Keccak-256 checksum together, and all five
have to be right at once for the checksum to match.

That is the whole offline evidence for this file's encoding half, and it is why the
address is here rather than in a fixture nobody reads.
"""

from __future__ import annotations

import hashlib
import inspect
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "swap_terminal"))

from chains.monero_keys import (
    CHECKSUM_BYTES,
    ENCODED_BLOCK_CHARS,
    MONERO_BASE58_ALPHABET,
    NETWORK_PREFIXES,
    STANDARD_BODY_BYTES,
    MoneroAddressError,
    MoneroKeyError,
    base58_decode,
    base58_encode,
    decode_address,
    encode_address,
    keccak256,
    public_key_for_share,
    shared_address,
    shared_private_spend_key,
    shared_public_key,
)
from modules.ed25519_group import (
    BASEPOINT,
    GROUP_ORDER,
    Point,
    is_canonical,
    is_torsion_free,
    scalar_base_mul,
)

# A real stagenet primary address from a real Monero wallet. Recorded in
# docs/monero_stagenet_funding.md as the faucet target; used here as the oracle.
STAGENET_ADDRESS = (
    "537wxk1vzCDembafqWxfTgNcZGoK6rAsbP1JHKiQkjYLLzNDtgMTUKACBguFzx2XnFf1FQVqogcjd9LXTQ52jGiVBV52C1V"
)

# Two private spend shares and two view shares. Fixed rather than random so a
# failure is reproducible, and deliberately of different bit lengths so a
# length-dependent bug in the scalar path cannot hide behind symmetry.
SPEND_SHARE_A = 0x0123456789ABCDEF
SPEND_SHARE_B = 0x0FEDCBA987654321FEDCBA9876543210FEDCBA9876543210FEDCBA98765432
VIEW_SHARE_A = 0x2222
VIEW_SHARE_B = 0x33333333333333333333


# --- 1. Keccak is the right function -------------------------------------------


def test_keccak256_is_keccak_and_not_sha3():
    """The guard on the dependency. Monero predates SHA-3 and uses original Keccak
    padding; hashlib's sha3_256 is the standardized one and gives a different
    digest for the same input. Reaching for it because the name is close produces
    addresses every wallet rejects."""
    assert keccak256(b"").hex() == "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
    assert hashlib.sha3_256(b"").hexdigest() == (
        "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a"
    )
    assert keccak256(b"") != hashlib.sha3_256(b"").digest()
    assert len(keccak256(b"abc")) == 32


# --- 2. The base58 block table, derived rather than trusted ---------------------


def test_the_block_size_table_is_recomputed_from_the_alphabet():
    """ENCODED_BLOCK_CHARS is ceil(log58(2^(8n))). Recomputed here from 58 and the
    byte widths, so the module's table cannot drift from its own definition."""
    assert len(MONERO_BASE58_ALPHABET) == 58
    assert len(set(MONERO_BASE58_ALPHABET)) == 58, "no repeated characters"
    for excluded in "0OIl":
        assert excluded not in MONERO_BASE58_ALPHABET

    derived = [0]
    for byte_count in range(1, 9):
        value = (1 << (8 * byte_count)) - 1
        characters = 0
        while value:
            value //= 58
            characters += 1
        derived.append(characters)
    assert tuple(derived) == ENCODED_BLOCK_CHARS == (0, 2, 3, 5, 6, 7, 9, 10, 11)


def test_base58_round_trips_over_every_block_remainder():
    """Nine payload lengths, so every possible final-block size is exercised. A
    decoder correct only for full blocks passes a single 8-byte test."""
    for length in range(1, 26):
        payload = bytes((index * 7 + 1) % 256 for index in range(length))
        assert base58_decode(base58_encode(payload)) == payload


def test_a_leading_zero_byte_inside_a_block_survives():
    """The difference from Bitcoin base58, and the one that fails silently.

    Bitcoin treats the payload as one integer, so leading zeros need a separate
    convention. Monero pads each fixed-width block instead. A payload whose first
    byte is zero must come back with that byte -- a Bitcoin decoder would lose it.
    """
    for payload in (b"\x00" * 8, b"\x00\x01\x02\x03\x04\x05\x06\x07", b"\x00" * 7 + b"\xff"):
        assert base58_decode(base58_encode(payload)) == payload


def test_a_character_outside_the_alphabet_is_refused_and_names_the_confusion():
    with pytest.raises(MoneroAddressError, match="not in Monero's base58 alphabet"):
        base58_decode("1111111111O")  # capital O, one of the four excluded
    with pytest.raises(MoneroAddressError, match="XRP Ledger"):
        base58_decode("1111111111O")


def test_an_impossible_final_block_length_is_refused():
    """1, 4 and 8 characters are not in the table -- no whole number of bytes encodes
    to them. A decoder that guessed a byte width for a final block of 4 would
    produce plausible bytes for a corrupt string instead of refusing it.

    Each string below is a full 11-character block plus a remainder of that length,
    so the failure is in the FINAL block specifically and not in a short input.
    """
    for remainder in (1, 4, 8):
        assert remainder not in ENCODED_BLOCK_CHARS, "premise: this length encodes nothing"
        with pytest.raises(MoneroAddressError, match="not a valid Monero block length"):
            base58_decode("1" * 11 + "1" * remainder)


def test_an_overlong_block_encoding_is_refused():
    """11 characters can express more than 2^64, so some 11-character strings decode
    to a value no 8 bytes can hold. A canonical address never contains one, and
    accepting it would mean two distinct strings decoding to the same bytes."""
    highest = MONERO_BASE58_ALPHABET[-1] * 11
    assert int.from_bytes(b"\xff" * 8, "big") < sum(
        57 * 58**power for power in range(11)
    ), "premise: 11 base58 characters overflow 8 bytes"
    with pytest.raises(MoneroAddressError, match="overlong encoding"):
        base58_decode(highest)


# --- 3. The real address: the oracle ------------------------------------------


def test_the_real_stagenet_address_decodes_and_its_checksum_matches():
    """Five things at once, and the checksum is what makes it a real test: the block
    decoder, the block-size table, the 1+32+32 body layout, the network byte and
    Keccak-256 all have to be right simultaneously or ecd59b10 does not come out."""
    assert len(STAGENET_ADDRESS) == 95

    raw = base58_decode(STAGENET_ADDRESS)
    assert len(raw) == STANDARD_BODY_BYTES + CHECKSUM_BYTES == 69
    assert keccak256(raw[:-CHECKSUM_BYTES])[:CHECKSUM_BYTES] == raw[-CHECKSUM_BYTES:]
    assert raw[-CHECKSUM_BYTES:].hex() == "ecd59b10"

    decoded = decode_address(STAGENET_ADDRESS)
    assert decoded.network == "stagenet"
    assert decoded.kind == "primary"
    assert decoded.prefix_byte == 24
    assert decoded.prefix_was_verified is True, (
        "this is the ONE prefix this repo has checked against a real address"
    )
    assert decoded.is_mainnet() is False
    assert decoded.public_spend_key.hex() == (
        "22089d0c183476e1ce35512ef816cb8137477048ada8f2838f63f99b1f784977"
    )
    assert decoded.public_view_key.hex() == (
        "81bf455adea75942ddcd1f0fe0be30e3367743722dbf0c31d76d4000ff29625c"
    )


def test_re_encoding_the_real_address_reproduces_it_byte_for_byte():
    """The bidirectional half. Decoding could be wrong in a way that re-encoding
    undoes, so this is not redundant with the test above only because the input is
    a string neither function produced."""
    decoded = decode_address(STAGENET_ADDRESS)
    assert encode_address("stagenet", decoded.public_spend_key, decoded.public_view_key) == (
        STAGENET_ADDRESS
    )


def test_both_public_keys_in_the_real_address_are_valid_group_elements():
    """A real wallet's keys are canonical, on-curve and torsion-free, which is the
    standard shared_public_key holds incoming shares to. If a real address failed
    this, the check would be too strict rather than the address wrong."""
    decoded = decode_address(STAGENET_ADDRESS)
    for key in (decoded.public_spend_key, decoded.public_view_key):
        assert is_canonical(key)
        assert is_torsion_free(Point.decompress(key))


def test_one_mistyped_character_is_caught_by_the_checksum():
    """Four bytes of checksum, so a mistype slips through with probability 2^-32.
    The message has to name Keccak-vs-sha3, because that is the other way to
    produce this failure and it is not a typo."""
    replacement = "E" if STAGENET_ADDRESS[-1] != "E" else "F"
    with pytest.raises(MoneroAddressError, match="checksum mismatch") as caught:
        decode_address(STAGENET_ADDRESS[:-1] + replacement)
    assert "Keccak-256" in str(caught.value)


def test_a_truncated_address_is_refused_before_the_checksum_is_consulted():
    with pytest.raises(MoneroAddressError, match=r"standard form|standard address"):
        decode_address(STAGENET_ADDRESS[:88])


def test_an_unknown_prefix_byte_says_the_checksum_passed(monkeypatch):
    """The refusal a mainnet or integrated address would hit. It must say the
    checksum VERIFIED, so a reader knows the gap is this repo's prefix table and
    not their address -- rule 14: state what the number means next to it."""
    decoded = decode_address(STAGENET_ADDRESS)
    body = bytes([99]) + decoded.public_spend_key + decoded.public_view_key
    forged = base58_encode(body + keccak256(body)[:CHECKSUM_BYTES])
    with pytest.raises(MoneroAddressError) as caught:
        decode_address(forged)
    message = str(caught.value)
    assert "prefix byte 99" in message
    assert "checksum VERIFIED" in message
    assert "24=stagenet/primary" in message


def test_only_stagenet_primary_is_marked_verified():
    """Rule 17 mechanically. Exactly one prefix in the table was checked against a
    real address; if a later session verifies another it must flip the flag here,
    and if somebody flips one without an address this test is the thing that
    should have stopped them."""
    verified = [p for p in NETWORK_PREFIXES if p.verified]
    assert len(verified) == 1
    assert (verified[0].network, verified[0].name, verified[0].byte) == ("stagenet", "primary", 24)


# --- 4. The shared key: the property the whole swap rests on -------------------


def test_the_sum_of_public_shares_is_the_public_key_of_the_summed_private_shares():
    """THE load-bearing assertion in this file.

    S_a + S_b == (s_a + s_b) * B. Without this the address is locked to a point
    that the recovered private key does not open, and the failure is silent: a
    valid address, a confirmed transfer, and no way to spend it. Point addition on
    one side, scalar addition mod l on the other -- two different operations in two
    different structures, and the swap is only atomic because they agree.
    """
    public_a = public_key_for_share(SPEND_SHARE_A)
    public_b = public_key_for_share(SPEND_SHARE_B)

    summed_publics = shared_public_key(public_a, public_b)
    public_of_summed = scalar_base_mul(
        shared_private_spend_key(SPEND_SHARE_A, SPEND_SHARE_B)
    ).compress()

    assert summed_publics == public_of_summed


def test_shared_public_key_commutes_so_both_parties_derive_one_address():
    """Neither side knows which share is "first". If this did not commute the two
    parties would compute different addresses and the swap would lock XMR to a
    place the other is not watching."""
    public_a = public_key_for_share(SPEND_SHARE_A)
    public_b = public_key_for_share(SPEND_SHARE_B)
    assert shared_public_key(public_a, public_b) == shared_public_key(public_b, public_a)


def test_the_shared_key_reduces_mod_l_rather_than_overflowing():
    """Two shares just under l sum above it. The private side must reduce and the
    public side must still agree -- this is the case docs/dleq_cross_curve_design.md
    section 3.2 flags, where a sum reduces on ed25519 and would not on secp256k1."""
    high_a = GROUP_ORDER - 3
    high_b = GROUP_ORDER - 5
    summed = shared_private_spend_key(high_a, high_b)
    assert summed == (high_a + high_b) % GROUP_ORDER
    assert summed < GROUP_ORDER
    assert shared_public_key(
        public_key_for_share(high_a), public_key_for_share(high_b)
    ) == scalar_base_mul(summed).compress()


def test_a_zero_share_is_refused_as_a_protocol_violation():
    """Zero makes the sum equal the other share alone, so one party holds the whole
    spend key. That is an attack, not a typo, and the message says so."""
    for arguments in ((0, SPEND_SHARE_B), (SPEND_SHARE_A, 0)):
        with pytest.raises(MoneroKeyError, match="is zero"):
            shared_private_spend_key(*arguments)


def test_the_identity_as_a_public_share_is_refused():
    """The public-side equivalent of a zero share."""
    identity = (BASEPOINT.add(BASEPOINT.negate())).compress()
    with pytest.raises(MoneroKeyError, match="is the identity"):
        shared_public_key(identity, public_key_for_share(SPEND_SHARE_A))


def test_a_share_at_or_above_the_group_order_is_refused_without_quoting_it():
    """A spend-key share must never appear in an exception message: those reach
    logs, tracebacks and bug reports. A bit length is enough to fix the call."""
    secret = GROUP_ORDER + 0xDEADBEEF
    with pytest.raises(MoneroKeyError) as caught:
        shared_private_spend_key(secret, SPEND_SHARE_B)
    message = str(caught.value)
    assert str(secret) not in message
    assert "deadbeef" not in message.lower()
    assert "bits" in message


def test_a_torsion_bearing_public_share_is_refused():
    """A share with a small-order component does not pin one point: several distinct
    encodings agree with it. An older libsodium's own predicate accepts an order-2
    component (see tests/test_ed25519_group.py); this refuses it."""
    order_two = bytes.fromhex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f")
    with pytest.raises(MoneroKeyError, match=r"torsion|identity"):
        shared_public_key(order_two, public_key_for_share(SPEND_SHARE_A))


# --- 5. The shared address, end to end ----------------------------------------


def test_shared_address_round_trips_and_carries_the_summed_keys():
    """Four shares in, one address out, and decoding it must give back the two sums
    -- not one sum and one party's key, which is the mistake that would let a
    single party watch the funds arrive."""
    spend_a, spend_b = public_key_for_share(SPEND_SHARE_A), public_key_for_share(SPEND_SHARE_B)
    view_a, view_b = public_key_for_share(VIEW_SHARE_A), public_key_for_share(VIEW_SHARE_B)

    address = shared_address("stagenet", spend_a, spend_b, view_a, view_b)
    decoded = decode_address(address)

    assert decoded.network == "stagenet"
    assert decoded.kind == "primary"
    assert len(address) == 95
    assert decoded.public_spend_key == shared_public_key(spend_a, spend_b)
    assert decoded.public_view_key == shared_public_key(view_a, view_b)
    assert decoded.public_spend_key != spend_a
    assert decoded.public_view_key != view_a


def test_shared_address_is_the_same_for_both_parties():
    """The agreement property, at the level that matters: the whole address string,
    with both sides' argument order swapped."""
    spend_a, spend_b = public_key_for_share(SPEND_SHARE_A), public_key_for_share(SPEND_SHARE_B)
    view_a, view_b = public_key_for_share(VIEW_SHARE_A), public_key_for_share(VIEW_SHARE_B)
    assert shared_address("stagenet", spend_a, spend_b, view_a, view_b) == shared_address(
        "stagenet", spend_b, spend_a, view_b, view_a
    )


def test_encode_address_has_no_default_network():
    """The cheapest guard against the most expensive typo. A defaulted network would
    let a test that meant stagenet emit a MAINNET address."""
    signature = inspect.signature(encode_address)
    assert signature.parameters["network"].default is inspect.Parameter.empty
    signature = inspect.signature(shared_address)
    assert signature.parameters["network"].default is inspect.Parameter.empty


def test_an_unknown_network_name_is_refused_and_lists_the_known_ones():
    with pytest.raises(MoneroAddressError, match="unknown network"):
        encode_address("mainnett", b"\x00" * 32, b"\x00" * 32)


def test_the_three_networks_produce_three_different_first_characters():
    """A stagenet address starts with 5, testnet with 9 or A, mainnet with 4. That
    is what an operator reads off the screen, so it is worth pinning even though
    only the stagenet byte is verified."""
    decoded = decode_address(STAGENET_ADDRESS)
    firsts = {
        network: encode_address(network, decoded.public_spend_key, decoded.public_view_key)[0]
        for network in ("mainnet", "testnet", "stagenet")
    }
    assert firsts["stagenet"] == "5"
    assert len(set(firsts.values())) == 3, f"networks must be distinguishable at a glance: {firsts}"
